MarkhamHillCoders/markhamhillportal

package-lock.json

Initial Branch

---

app.js
bin/www
package-lock.json
package.json
steps.md

Daniel's Branch to Master

---

docs/readme.md

add Read Me in Docs

---

docs/readme.md
steps.md

Change Read Me

---

.circleci/config.yml

add CircleCI

---

package.json
yarn.lock

M< Daniel Core

---

package.json

Fixes from Daniel core

---

package.json

reinstall @angular-devkit

---

.circleci/config.yml
src/app/app.component.html
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/app.module.ts

Daniel fixing bugs

---

package.json
src/app/app.module.ts
src/app/profile/profile.component.html
src/app/profile/profile.component.spec.ts
src/app/profile/profile.component.ts

add profiles

---

yarn.lock

+ Yarn Lock

---

src/app/app.module.ts
src/app/header/header.component.html
src/app/header/header.component.spec.ts
src/app/header/header.component.ts

add header

---

.circleci/config.yml
src/app/about/about.component.html
src/app/about/about.component.spec.ts
src/app/about/about.component.ts
src/app/app.module.ts
src/app/footer/footer.component.html
src/app/footer/footer.component.spec.ts
src/app/footer/footer.component.ts
src/app/resources/resources.component.html
src/app/resources/resources.component.spec.ts
src/app/resources/resources.component.ts
src/app/sidebar/sidebar.component.html
src/app/sidebar/sidebar.component.spec.ts
src/app/sidebar/sidebar.component.ts
src/index.html

M < Daniel

---

src/app/app.component.css
src/app/app.component.html

Daniel > Master

---

github-steps.md
src/app/app.component.css
src/app/app.component.html

Daniel + Update GitHub Steps

---

github-steps.md

Order of commands need to be checked.  Comments needed.

Connect your remote branch to your local branch

---

github-steps.md

To delete a branch

---

github-steps.md

Daniel's branch

---

README.md
docs/readme.md

Daniel > Master (base)

---

docs/readme.md
package-lock.json
package.json

(c) Sync Daniel > Master (B)

---

README.md
app.js
routes/login.js
src/app/components/navbar/navbar.component.html
src/app/user/user.service.ts

Daniel > m

---

package.json

Daniel core

---

yarn.lock

Daniel core's new yarn lock

---

docs/steps.md

update steps :: autho> master

---

docs/steps.md
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/components/login/login.component.html

Autho > master

---

README.md
src/app/app.component.html
src/app/components/directory/directory.component.html
src/index.html

Daniel: Update for list
